---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: light
  test_sequence:
    - dependency
    - syntax
